all:
	g++ MainTrain.cpp anomaly_detection_util.cpp timeseries.cpp SimpleAnomalyDetector.cpp -g -o a.out
	./a.out
compile:
	g++ MainTrain.cpp anomaly_detection_util.cpp timeseries.cpp SimpleAnomalyDetector.cpp -g -o a.out
run:
	./a.out