all:
	g++ MainTrain.cpp anomaly_detection_util.cpp timeseries.cpp SimpleAnomalyDetector.cpp minCircle.cpp HybridAnomalyDetector.cpp CLI.cpp -std=c++11 -g -o a.out
	./a.out
compile:
	g++ MainTrain.cpp anomaly_detection_util.cpp timeseries.cpp SimpleAnomalyDetector.cpp minCircle.cpp HybridAnomalyDetector.cpp CLI.cpp -std=c++11 -g -o a.out
run:
	./a.out
clean:
	rm *.out *.csv